api = "0.10"

[buildpack]
  id = "neeto-deploy/procfile"
  version = "5.11.3"
  name = "neetodeploy Procfile"
  homepage = "https://github.com/bigbinary/buildpacks-procfile"
  description = "A Cloud Native Buildpack that processes Procfile declarations"
  keywords = ["procfile", "processes"]
  clear-env = false

  [[buildpack.licenses]]
    type = "BSD-3-Clause"

# Support all stacks for maximum compatibility
[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "heroku-20"

[[stacks]]
  id = "heroku-22"

[[stacks]]
  id = "*"

[metadata]
  include-files = [
    "bin/build",
    "bin/detect",
    "bin/buildpack",
    "bin/install-deps",
    "lib/buildpack.rb",
    "lib/procfile.rb",
    "buildpack.toml",
    "Gemfile",
    "Gemfile.lock",
  ]

[metadata.configuration]
  default-process = { default = "web" }

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
